// Classify distinct INPUT TUPLES with the real assignStage, and emit the SQL
// that applies the result.
//
// The DB is only reachable here through the Supabase MCP, not with a service
// key, so the backfill cannot be a straight "read rows, write rows" script.
// assignStage is a pure function of a handful of fields though, so classifying
// the 600 DISTINCT input tuples is equivalent to classifying all 2,213 rows and
// small enough to move through the tool boundary.
//
// It still runs the real classifier. Porting the rules to SQL would be quicker
// and would drift from the TypeScript the moment either changed, which is the
// exact class of bug this backfill exists to repair.

import { readFileSync, writeFileSync } from 'fs'
import { assignStage, type StageKey } from '../lib/segmentation-v2'
import type { StoredSubmission } from '../lib/kv'

const V2_FILE = process.argv[2]
if (!V2_FILE) throw new Error('usage: classify-tuples.ts <v2-payload-file>')

/** Pull the JSON array out of whatever wrapper the tool result arrived in. */
function extractJsonArray(raw: string): unknown[] {
  const start = raw.indexOf('[{')
  if (start < 0) throw new Error('no JSON array found in payload')
  let depth = 0
  for (let i = start; i < raw.length; i++) {
    if (raw[i] === '[') depth++
    else if (raw[i] === ']') { depth--; if (depth === 0) return JSON.parse(raw.slice(start, i + 1)) }
  }
  throw new Error('unterminated JSON array')
}

const base = (): StoredSubmission => ({
  id: '', name: '', email: '', aiLevel: '', mainGoal: '', aiTools: '', createdAt: '',
} as unknown as StoredSubmission)

interface V2Tuple { fq: number | null; dp: number | null; br: number | null; da: string | null; n: number }

const raw = readFileSync(V2_FILE, 'utf8')
const tuples = extractJsonArray(raw) as V2Tuple[]

const out: { fq: number | null; dp: number | null; br: number | null; da: string | null; stage: StageKey; score: number; reason: string; n: number }[] = []
const dist = new Map<string, number>()

for (const t of tuples) {
  const s: StoredSubmission = {
    ...base(),
    frequencyScore: t.fq ?? undefined,
    depthScore: t.dp ?? undefined,
    breadthScore: t.br ?? undefined,
    depthActions: t.da ?? undefined,
  }
  const r = assignStage(s)
  out.push({ fq: t.fq, dp: t.dp, br: t.br, da: t.da, stage: r.stage, score: r.score, reason: r.reason, n: t.n })
  dist.set(r.stage, (dist.get(r.stage) ?? 0) + t.n)
}

const total = out.reduce((a, x) => a + x.n, 0)
console.log(`classified ${out.length} distinct tuples covering ${total} rows\n`)
console.log('resulting distribution (v2-path rows only):')
for (const k of Array.from(dist.keys()).sort()) {
  const n = dist.get(k)!
  console.log(`  ${k.padEnd(18)} ${String(n).padStart(5)}  ${(100 * n / total).toFixed(1)}%`)
}

const q = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`)
const num = (v: number | null) => (v === null ? 'null' : String(v))
const values = out.map(x =>
  `(${num(x.fq)},${num(x.dp)},${num(x.br)},${q(x.da)},'${x.stage}',${x.score},${q(x.reason)})`).join(',\n')

writeFileSync('/tmp/claude-0/-home-user-ai-central-quiz/a33aa7e6-2ccc-5034-8c71-923d41f6dfdd/scratchpad/backfill-v2.sql',
`-- v2-path stage backfill, generated by scripts/classify-tuples.ts from the real assignStage.
with m(fq,dp,br,da,stage,score,reason) as (values
${values}
)
update submissions s set
  stage = m.stage, stage_score = m.score, stage_reason = m.reason, staged_at = now()
from m
where coalesce(s.is_test,false) = false
  and s.stage is not null
  and (s.frequency_score is not null or s.depth_score is not null or s.breadth_score is not null)
  and s.frequency_score is not distinct from m.fq
  and s.depth_score      is not distinct from m.dp
  and s.breadth_score    is not distinct from m.br
  and s.depth_actions    is not distinct from m.da
  and s.stage is distinct from m.stage;
`)
console.log('\nwrote backfill-v2.sql')
